#!/bin/sh -e

NETOM_ETC="/etc/netom"

case "$1" in
purge)
    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."
    if [ -d ${NETOM_ETC} ]; then
        rm -R ${NETOM_ETC}
    fi
    ;;
esac

#DEBHELPER#