#!/bin/sh -e

NETOM_HOME="/var/lib/netom/"
NETOM_USER="netom"

create_user() {
    if id ${NETOM_USER} > /dev/null 2>&1; then return; fi
    adduser --system --home "${NETOM_HOME}" --group ${NETOM_USER}
}

case "$1" in
configure)
    create_user
    ;;
esac

#DEBHELPER#