name: Build DEB packages

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      apt-suites:
        value: ${{ jobs.build.outputs.apt-suites }}

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/pkg-build.yml
    with:
      package-format: deb
      build-images: false
